// Auto-generated by generateReturnTypes.js - do not edit manually
import { GENRE_LABEL_PROPERTIES } from "./GenreLabelView";
import { USER_LABEL_PROPERTIES } from "./UserLabelView";
import { DIRECTOR_LABEL_PROPERTIES } from "./DirectorLabelView";
import { PERSON_LABEL_PROPERTIES } from "./PersonLabelView";
import { ACTOR_LABEL_PROPERTIES } from "./ActorLabelView";
import { MOVIE_LABEL_PROPERTIES } from "./MovieLabelView";

export const ALIAS_TYPE_TO_PROPERTIES_MAP: Record<string, { key: string; type: string }[]> = {
  Genre: GENRE_LABEL_PROPERTIES,
  User: USER_LABEL_PROPERTIES,
  Director: DIRECTOR_LABEL_PROPERTIES,
  Person: PERSON_LABEL_PROPERTIES,
  Actor: ACTOR_LABEL_PROPERTIES,
  Movie: MOVIE_LABEL_PROPERTIES,
};
